# Generated by Django 3.2 on 2022-12-07 13:29

from django.db import migrations, models
import django.db.models.deletion
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', validators=[validators.ProjectValidator()]),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
