# Generated by Django 3.2 on 2022-12-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_content_type_and_object_id_is_not_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
