# Generated by Django 3.2 on 2022-10-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0004_change_testplan_parent_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='execution_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
