version: '3.9'
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: ${LOKI_URL}
services:
  testy:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: testy
      dockerfile: scripts/prod/Dockerfile
    volumes:
      - './:/testy'
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=testy.settings.production
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVICE_HOST=${POSTGRES_SERVICE_HOST}
      - POSTGRES_SERVICE_PORT=${POSTGRES_SERVICE_PORT}
      - COMPANY_DOMAIN=${COMPANY_DOMAIN}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOCAL_SESSION=${LOCAL_SESSION}
      - DSN=${DSN}
    depends_on:
      db:
        condition: service_healthy
    <<: *logging
  db:
    image: postgres:14.5-alpine
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    <<: *logging
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - "./redis_data:/data"
    ports:
      - "6380:6379"
    <<: *logging
  celery:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    build:
      context: testy
      dockerfile: scripts/celery/Dockerfile
    command: celery -A testy worker -l INFO
    environment:
      - DJANGO_SETTINGS_MODULE=testy.settings.development
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVICE_HOST=${POSTGRES_SERVICE_HOST}
      - POSTGRES_SERVICE_PORT=${POSTGRES_SERVICE_PORT}
      - COMPANY_DOMAIN=${COMPANY_DOMAIN}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOCAL_SESSION=${LOCAL_SESSION}
      - DSN=${DSN}
    volumes:
      - './testy:/testy'
    depends_on:
      - testy
      - db
      - redis
    <<: *logging