version: '3.9'
services:
  tms:
    build:
      context: ./tms
      dockerfile: scripts/dev/Dockerfile
    volumes:
      - './tms:/tms'
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=tms.settings.development
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVICE_HOST=${POSTGRES_SERVICE_HOST}
      - POSTGRES_SERVICE_PORT=${POSTGRES_SERVICE_PORT}
      - COMPANY_DOMAIN=${COMPANY_DOMAIN}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:14.5-alpine
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}