version: '3.9'
services:
  tms:
    build:
      context: .
      dockerfile: scripts/dev/Dockerfile
    volumes:
      - './tms:/opt/tms'
    ports:
      - 8001:8000
    environment:
      - DJANGO_SETTINGS_MODULE=tms.settings.development
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  db:
    image: postgres:14.5-alpine
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 5435:5435
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres