# Generated by Django 3.2 on 2022-09-11 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tests_description', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('setup', models.TextField()),
                ('scenarion', models.TextField()),
                ('teardown', models.TextField()),
                ('estimate', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='core.project')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='tests_description.testsuite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
