# Generated by Django 3.2 on 2022-10-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0003_auto_20220912_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='scenarion',
            new_name='scenario',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
