# Generated by Django 3.2 on 2022-10-05 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221005_2023'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests_description', '0003_auto_20220912_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='scenarion',
            new_name='scenario',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='lft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='rght',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='tree_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.CreateModel(
            name='HistoricalTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('estimate', models.PositiveIntegerField()),
                ('history_change_reason', models.CharField(max_length=255, null=True)),
                ('history_date', models.DateTimeField(null=True)),
                ('history_type', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('scenario', models.TextField()),
                ('setup', models.TextField()),
                ('teardown', models.TextField()),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_test_cases', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_test_cases', to='core.project')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_test_cases', to='tests_description.testsuite')),
            ],
            options={
                'default_related_name': 'historical_test_cases',
            },
        ),
    ]
