# Generated by Django 3.2 on 2022-10-14 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tests_representation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testplan',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='core.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='core.project'),
            preserve_default=False,
        ),
    ]
