# Generated by Django 3.2.4 on 2022-12-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0005_testresult_execution_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
