# Generated by Django 3.2 on 2022-12-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0005_testresult_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
