# Generated by Django 3.2.4 on 2023-01-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0006_added_testplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
