# Generated by Django 3.2.4 on 2023-01-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0009_testresult_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestresult',
            name='status',
            field=models.IntegerField(choices=[(0, 'Failed'), (1, 'Passed'), (2, 'Skipped'), (3, 'Broken'), (4, 'Blocked'), (5, 'Untested'), (6, 'Retest')], default=5),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.IntegerField(choices=[(0, 'Failed'), (1, 'Passed'), (2, 'Skipped'), (3, 'Broken'), (4, 'Blocked'), (5, 'Untested'), (6, 'Retest')], default=5),
        ),
    ]
