version: '3.9'
services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - "./loki-data:/loki"
    container_name: "loki"
    networks:
      - "testy_default"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3200:3200"
    environment:
      - GF_SERVER_HTTP_PORT=3200
    volumes:
      - "./grafana-data:/var/lib/grafana"
    container_name: "grafana"
    networks:
      - "testy_default"
networks:
  testy_default:
    name: testy_default