# Generated by Django 3.2 on 2022-12-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestcase',
            name='scenario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='scenario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
