# Generated by Django 3.2.4 on 2023-01-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0002_added_description_testcase_testsuite'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestcase',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
