# Generated by Django 3.2 on 2022-12-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestrailBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestrailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('api_url', models.CharField(max_length=255)),
                ('dumpfile_path', models.CharField(max_length=255)),
            ],
        ),
    ]
