server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml # This location needs to be writeable by Promtail.

clients:
  - url: https://testy-dev.set.yadro.com:3101/loki/api/v1/push

scrape_configs:
  - job_name: nginx_dev
    static_configs:
      - labels:
          job: nginx_access_dev  # A `job` label is fairly standard in prometheus and useful for linking metrics and logs.
          host: testy-dev.set.yadro.com # A `host` label will help identify logs from this machine vs others
          __path__: /var/log/nginx/access.*  # The path matching uses a third party library: https://github.com/bmatcuk/doublestar
      - labels:
          job: nginx_error_dev  # A `job` label is fairly standard in prometheus and useful for linking metrics and logs.
          host: testy-dev.set.yadro.com # A `host` label will help identify logs from this machine vs others
          __path__: /var/log/nginx/error.*  # The path matching uses a third party library: https://github.com/bmatcuk/doublestar